import fs from 'fs';

const GENERATED_AT = new Date().toISOString();

const SOURCES = {
  kyoiku: {
    label: 'Kyoiku kanji list',
    owner: 'fnshr',
    repo: 'kyo-kan',
    branch: 'master',
    candidates: ['kyoiku-kanji-2020.csv', 'kyoiku-kanji-2017.csv'],
    outputPath: 'scripts/kyoiku.csv',
  },
  ids: {
    label: 'CJKVI IDS database',
    owner: 'cjkvi',
    repo: 'cjkvi-ids',
    branch: 'master',
    candidates: ['ids.txt'],
    outputPath: 'scripts/ids.txt',
    licenseFallback: {
      name: 'ids.txt follows CHISE project terms; other upstream data is GPLv2 per cjkvi-ids README',
      spdxId: null,
      url: 'https://github.com/cjkvi/cjkvi-ids#licenses',
    },
  },
};

async function fetchJson(url) {
  const res = await fetch(url, { headers: { Accept: 'application/vnd.github+json' } });
  if (!res.ok) {
    throw new Error(`${res.status} ${res.statusText}: ${url}`);
  }
  return res.json();
}

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`${res.status} ${res.statusText}: ${url}`);
  }
  return res.text();
}

async function repoMetadata(source) {
  const repoApi = `https://api.github.com/repos/${source.owner}/${source.repo}`;
  const commit = await fetchJson(`${repoApi}/commits/${source.branch}`);
  let license = null;
  try {
    const licenseData = await fetchJson(`${repoApi}/license`);
    license = {
      name: licenseData.license?.name ?? null,
      spdxId: licenseData.license?.spdx_id ?? null,
      url: licenseData.html_url ?? null,
    };
  } catch (error) {
    license = {
      ...(source.licenseFallback ?? {
        name: null,
        spdxId: null,
        url: `https://github.com/${source.owner}/${source.repo}`,
      }),
      note: `GitHub license API failed: ${error.message}`,
    };
  }

  return {
    repository: `https://github.com/${source.owner}/${source.repo}`,
    branch: source.branch,
    commit: commit.sha,
    commitUrl: commit.html_url,
    license,
  };
}

function rawUrl(source, ref, path) {
  return `https://raw.githubusercontent.com/${source.owner}/${source.repo}/${ref}/${path}`;
}

function webUrl(source, ref, path) {
  return `https://github.com/${source.owner}/${source.repo}/blob/${ref}/${path}`;
}

async function fetchPinnedSource(source) {
  console.log(`Fetching ${source.label} metadata...`);
  const metadata = await repoMetadata(source);

  const errors = [];
  for (const path of source.candidates) {
    const url = rawUrl(source, metadata.commit, path);
    try {
      const text = await fetchText(url);
      fs.writeFileSync(source.outputPath, text);
      return {
        ...metadata,
        label: source.label,
        path,
        outputPath: source.outputPath,
        rawUrl: url,
        webUrl: webUrl(source, metadata.commit, path),
        candidatePaths: source.candidates,
        bytes: Buffer.byteLength(text, 'utf8'),
      };
    } catch (error) {
      errors.push(`${path}: ${error.message}`);
    }
  }

  throw new Error(`Failed to fetch ${source.label}: ${errors.join('; ')}`);
}

async function run() {
  const metadata = {
    generatedAt: GENERATED_AT,
    note: 'Generated by scripts/fetch_kanji_data.mjs. Raw files are fetched from pinned GitHub commits for reproducibility.',
    sources: {},
  };

  try {
    metadata.sources.kyoiku = await fetchPinnedSource(SOURCES.kyoiku);
    console.log(`Fetched ${metadata.sources.kyoiku.path}`);

    metadata.sources.ids = await fetchPinnedSource(SOURCES.ids);
    console.log(`Fetched ${metadata.sources.ids.path}`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
    return;
  }

  fs.writeFileSync('scripts/data_sources.json', `${JSON.stringify(metadata, null, 2)}\n`);
  console.log('Saved raw files and scripts/data_sources.json.');
}

run();


